app = "lingering-wood-1850"

[env]
  RAILS_ENV = "production"


[http_service]
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  protocol = "tcp"

[deploy]
  release_command = "bin/rails db:prepare"

