# fly.toml app configuration file generated for cool-lake-5286 on 2023-07-10T09:21:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cool-lake-5286"
primary_region = "ewr"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
